# Generated by Django 3.2.7 on 2023-08-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_user_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='parent_reply',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_count',
        ),
    ]
