# Generated by Django 3.2.7 on 2023-10-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20230921_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed_languages',
            field=models.ManyToManyField(blank=True, related_name='followers', to='base.Language'),
        ),
    ]
